name: lian
description: A Flutter app using FFmpeg and modern packages.
publish_to: "none" # يمنع النشر إلى pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # مكتبة FFmpeg مدعومة رسمياً من Maven Central
  ffmpeg_kit_flutter: ^6.0.3

  # مكتبات أساسية
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  permission_handler: ^11.4.0
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
